name: 'XAPI Github Actions'
description: 'Calls a Cisco XAPI endpoint and displays xStatus data'
inputs:
  api-endpoint-url:   #ID of input
    description: 'The endpoint to call'
    required: true
    #default: ''
  destination-filter:
    description: 'Filter applied to endpoint action'
    required: false    
runs:
  using: 'node16'
  main: 'index.js'
